public enum Accao {
    LUTAR, CORRER, ESCONDER, VOAR, NADAR, EXPLORAR, RESGATAR, INVADIR, CAÇAR, ESCALAR,
    DESCOBRIR, PROTEGER, DEFENDER, ENFEITIÇAR, CAMUFLAR, CONSTRUIR, CRIAR, CURAR, CONTROLAR,
    DOMINAR, SEDUZIR, ENGANAR, MENTIR, ESCAVAR, SALVAR, ESPIAR, CAPTURAR, SABOTAR, VIGIAR, COMANDAR
}