public enum Lugar {
    CASTELO, FLORESTA, CAVERNA, MONTANHA, DESERTO, OCEANO, ILHA, PLANETA, NAVE, CIDADE,
    VILA, TEMPLO, PIRÂMIDE, FORTALEZA, MAUSOLÉU, PRISÃO, LABIRINTO, GALERIA, JARDIM, CRIPTA,
    MANSÃO, SUBMARINO, SANTUÁRIO, PÂNTANO, CACHOEIRA, MERCADO, BIBLIOTECA, ESCOLA, PALÁCIO, PLANÍCIE
}