public enum Personagem {
    CAVALEIRO, MÁGICO, REI, RAINHA, PIRATA, DRAGÃO, ROBÔ, ALIENÍGENA, VAMPIRO, DETETIVE,
    GUERREIRO, SAMURAI, NINJA, ASTRONAUTA, ZUMBI, ESPADACHIM, ELFO, GNOMO, FADA, ASSASSINO,
    MONSTRO, CAÇADOR, SÁBIO, HERÓI, VILÃO, FEITICEIRO, CIENTISTA, LADRÃO, ANJO, DEMÔNIO
}